/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_convertedfiles_free: (a: number, b: number) => void;
export const __wbg_options_free: (a: number, b: number) => void;
export const convert_ifc: (a: number, b: number, c: number, d: number) => [number, number, number];
export const convert_ifc_tdp: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const convertedfiles_bytes: (a: number, b: number) => [number, number];
export const convertedfiles_is_empty: (a: number) => number;
export const convertedfiles_len: (a: number) => number;
export const convertedfiles_mesh_count: (a: number) => number;
export const convertedfiles_name: (a: number, b: number) => [number, number];
export const convertedfiles_schema: (a: number) => [number, number];
export const convertedfiles_triangle_count: (a: number) => number;
export const inspect_ifc: (a: number, b: number) => [number, number, number, number];
export const options_new: () => number;
export const options_set_mode: (a: number, b: number, c: number) => void;
export const options_set_openings: (a: number, b: number, c: number) => void;
export const options_set_quality: (a: number, b: number, c: number) => void;
export const options_set_recenter: (a: number, b: number) => void;
export const options_set_source_name: (a: number, b: number, c: number) => void;
export const options_set_spaces: (a: number, b: number, c: number) => void;
export const options_set_split: (a: number, b: number, c: number) => void;
export const version: () => [number, number];
export const start: () => void;
export const meshopt_wasm_alloc: (a: number) => number;
export const meshopt_wasm_free: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
