import { hl } from './hlCode';

declare const __APP_VERSION__: string;
const TGZ = `tredespace-ui-${__APP_VERSION__}.tgz`;

/** Download card for the @tredespace/ui npm package (built by pack-ui.mjs and
 *  emitted next to this page by the uiPackage() Vite plugin — build only). */
export function PackageCard() {
  return (
    <section style={{ marginBottom: 28 }}>
      <div className="sdk-card">
        <div className="sdk-copy">
          <p className="sec-kick">The package</p>
          <h2>
            <code>@tredespace/ui</code>
          </h2>
          <p>
            Everything on this page as an npm package (MIT): compiled ESM + TypeScript declarations. Drop the tarball in
            your repo and depend on it as a file — its own dependencies install automatically. You provide two things:{' '}
            <b>React 19</b> (peer dependency) and <b>Tailwind CSS v4</b> in your build (a build tool can't ship inside a
            package). Full setup in the README inside the tarball.
            {import.meta.env.DEV && <b> Dev server note: the tarball is generated by the production build.</b>}
          </p>
        </div>
        <div className="sdk-actions">
          <a className="btn btn-primary" href={`./${TGZ}`} download>
            Download {TGZ}
          </a>
        </div>
      </div>
      <pre className="code" style={{ marginTop: 12 }}>
        {hl(`// package.json — install from the downloaded file; its deps come along
"dependencies": {
  "@tredespace/ui": "file:./libs/${TGZ}"
}

// one-time: Tailwind v4 in your build (the only manual install)
npm i -D tailwindcss @tailwindcss/vite

// app.css — the widgets are Tailwind-styled: import the library theme
// and let Tailwind v4 scan the package (node_modules isn't scanned by default)
@import "tailwindcss";
@import "@tredespace/ui/styles.css";
@source "../node_modules/@tredespace/ui";

// then import away
import { Button, Select, initTooltips } from '@tredespace/ui/widgets';
import { DockView, definePanel, split, tabs, useDockManager } from '@tredespace/ui/dockable';`)}
      </pre>
    </section>
  );
}
