import { IconExternalLink, IconLicense, IconX } from '@tabler/icons-react';
import { Button, Collapsible, Modal, TextInput, TitleBar } from '@treDeSpaceUI/widgets';
import { useState } from 'react';

interface Notice {
  name: string;
  version: string;
  license: string | null;
  link: string | null;
  text: string | null;
  kind: 'npm' | 'rust';
}

const KIND_LABEL: Record<Notice['kind'], string> = { npm: 'npm packages', rust: 'Rust crates' };

/** Button in Settings → About that opens the bundled third-party license texts.
 *  Data is generated by scripts/gen-third-party-notices.mjs and lazy-loaded so
 *  the (large) license blob stays out of the initial bundle. */
export function ThirdPartyNotices() {
  const [open, setOpen] = useState(false);
  const [packages, setPackages] = useState<Notice[] | null>(null);
  const [filter, setFilter] = useState('');

  async function show() {
    setOpen(true);
    if (!packages) {
      const mod = await import('../../../../generated/third-party-notices.json');
      setPackages((mod.default as { packages: Notice[] }).packages);
    }
  }

  const q = filter.trim().toLowerCase();
  const shown = (packages ?? []).filter((p) => !q || p.name.toLowerCase().includes(q));
  const groups: Notice['kind'][] = ['npm', 'rust'];

  return (
    <>
      <Button icon={<IconLicense size={14} />} onClick={show} tooltip="License texts for every bundled dependency">
        Show third-party notices
      </Button>

      {open && (
        <Modal z={2000} onKeyDown={(e) => e.key === 'Escape' && setOpen(false)}>
          <div className="flex h-[80vh] w-[min(680px,92vw)] flex-col border border-slate-600 bg-slate-900 shadow-black/50 shadow-xl">
            <TitleBar icon={<IconLicense size={16} className="shrink-0 text-blue-400" />}>
              <span>Third-party notices</span>
              <button
                type="button"
                className="ml-auto cursor-pointer text-slate-400 hover:text-slate-200"
                onClick={() => setOpen(false)}
                aria-label="Close"
              >
                <IconX size={15} />
              </button>
            </TitleBar>

            <div className="border-slate-800 border-b p-2">
              <TextInput value={filter} onChange={setFilter} placeholder="Filter by name…" />
              <p className="mt-1.5 text-[11px] text-slate-500 leading-relaxed">
                This product bundles the open-source components below. Each is used under its own license, reproduced in
                full. Development-only tooling is not distributed and is not listed.
              </p>
            </div>

            <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto p-2">
              {packages == null ? (
                <div className="p-4 text-center text-slate-500 text-xs">Loading…</div>
              ) : (
                groups.map((kind) => {
                  const items = shown.filter((p) => p.kind === kind);
                  if (items.length === 0) {
                    return null;
                  }
                  return (
                    <Collapsible key={kind} title={KIND_LABEL[kind]} aside={items.length} defaultOpen={q !== ''}>
                      {items.map((p) => (
                        <Collapsible
                          key={`${p.name}@${p.version}`}
                          defaultOpen={false}
                          title={
                            <span className="flex min-w-0 flex-1 items-baseline gap-2">
                              <span className="truncate text-slate-200">{p.name}</span>
                              <span className="shrink-0 font-mono text-[11px] text-slate-500">{p.version}</span>
                              <span className="ml-auto shrink-0 text-[11px] text-emerald-400/80">
                                {p.license ?? 'see text'}
                              </span>
                            </span>
                          }
                        >
                          {p.link && (
                            <a
                              href={p.link}
                              target="_blank"
                              rel="noreferrer noopener"
                              className="inline-flex items-center gap-1 text-blue-400 text-xs hover:underline"
                            >
                              <IconExternalLink size={12} />
                              {p.link}
                            </a>
                          )}
                          <pre className="max-h-72 overflow-auto whitespace-pre-wrap break-words bg-slate-950/60 p-2 font-mono text-[11px] text-slate-400 leading-relaxed">
                            {p.text ?? 'No license text bundled — see the project link above.'}
                          </pre>
                        </Collapsible>
                      ))}
                    </Collapsible>
                  );
                })
              )}
              {packages != null && shown.length === 0 && (
                <div className="p-4 text-center text-slate-500 text-xs">No packages match “{filter}”.</div>
              )}
            </div>
          </div>
        </Modal>
      )}
    </>
  );
}
