import { IconExternalLink, IconLicense } from '@tabler/icons-react';
import { Badge, Button, Collapsible, DialogFrame, EmptyState, Link, Spinner, TextInput } from '@treDeSpaceUI/widgets';
import { useState } from 'react';

interface Notice {
  name: string;
  version: string;
  license: string | null;
  link: string | null;
  text: string | null;
  kind: 'npm' | 'rust';
}

const KIND_LABEL: Record<Notice['kind'], string> = { npm: 'npm packages', rust: 'Rust crates' };
const GROUPS: readonly Notice['kind'][] = ['npm', 'rust'];

/** One package block: name, version, license badge, link and full text. */
function NoticeEntry({ p }: { p: Notice }) {
  return (
    <Collapsible
      defaultOpen={false}
      title={
        <span className="flex min-w-0 flex-1 items-baseline gap-2">
          <span className="truncate text-slate-200">{p.name}</span>
          <span className="shrink-0 font-mono text-[11px] text-slate-500">{p.version}</span>
        </span>
      }
      aside={<Badge tone="success">{p.license ?? 'see text'}</Badge>}
    >
      {p.link && (
        <Link href={p.link} className="inline-flex items-center gap-1 no-underline hover:underline">
          <IconExternalLink size={12} />
          {p.link}
        </Link>
      )}
      <pre className="max-h-72 overflow-auto whitespace-pre-wrap break-words bg-slate-950/60 p-2 font-mono text-[11px] text-slate-400 leading-relaxed">
        {p.text ?? 'No license text bundled — see the project link above.'}
      </pre>
    </Collapsible>
  );
}

/** Button in Settings → About that opens the bundled third-party license texts.
 *  Data is generated by scripts/gen-third-party-notices.mjs and lazy-loaded so
 *  the (large) license blob stays out of the initial bundle. */
export function ThirdPartyNotices() {
  const [open, setOpen] = useState(false);
  const [packages, setPackages] = useState<Notice[] | null>(null);
  const [filter, setFilter] = useState('');

  async function show() {
    setOpen(true);
    if (!packages) {
      const mod = await import('../../../../generated/third-party-notices.json');
      setPackages((mod.default as { packages: Notice[] }).packages);
    }
  }

  const q = filter.trim().toLowerCase();
  const shown = (packages ?? []).filter((p) => !q || p.name.toLowerCase().includes(q));

  return (
    <>
      <Button icon={<IconLicense size={14} />} onClick={show} tooltip="License texts for every bundled dependency">
        Show third-party notices
      </Button>

      {open && (
        <DialogFrame
          icon={<IconLicense size={16} className="shrink-0 text-blue-400" />}
          title="Third-party notices"
          width="min(680px, 92vw)"
          height="80vh"
          onClose={() => setOpen(false)}
          bodyClassName="flex min-h-0 flex-1 flex-col overflow-hidden"
        >
          <div className="shrink-0 border-slate-800 border-b p-2">
            <TextInput type="search" value={filter} onChange={setFilter} placeholder="Filter by name…" />
            <p className="mt-1.5 text-[11px] text-slate-500 leading-relaxed">
              This product bundles the open-source components below. Each is used under its own license, reproduced in
              full. Development-only tooling is not distributed and is not listed.
            </p>
          </div>

          <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto p-2">
            {packages == null ? (
              <EmptyState layout="center" icon={<Spinner size={18} />}>
                Loading…
              </EmptyState>
            ) : (
              GROUPS.map((kind) => {
                const items = shown.filter((p) => p.kind === kind);
                if (items.length === 0) {
                  return null;
                }
                return (
                  <Collapsible key={kind} title={KIND_LABEL[kind]} aside={items.length} defaultOpen={q !== ''}>
                    {items.map((p) => (
                      <NoticeEntry key={`${p.name}@${p.version}`} p={p} />
                    ))}
                  </Collapsible>
                );
              })
            )}
            {packages != null && shown.length === 0 && (
              <EmptyState layout="center">No packages match “{filter}”.</EmptyState>
            )}
          </div>
        </DialogFrame>
      )}
    </>
  );
}
